; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = espidf

; USB Serial/JTAG monitor (GPIO18/GPIO19 on ESP32-C3)
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Use the board's USB port for upload and monitor
upload_protocol = esp-builtin
